# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20170726_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_check',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packageupdate',
            name='status',
            field=models.IntegerField(choices=[(0, 'UP TO DATE'), (1, 'UPDATES AVAILABLE'), (2, 'IGNORED'), (3, 'INSTALL'), (4, 'ERROR')], default=1),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(default='127.1.1.1'),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.IntegerField(choices=[(0, 'UP TO DATE'), (1, 'UPDATES AVAILABLE'), (2, 'IGNORED'), (3, 'INSTALL'), (4, 'ERROR')], default=3),
        ),
    ]
