# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20170727_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='last_check',
            field=models.DateTimeField(blank=True),
        ),
    ]
