# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20170727_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Debian'), (1, 'Centos'), (2, 'Ubuntu')], null=True),
        ),
    ]
