# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20170727_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='install',
        ),
        migrations.AlterField(
            model_name='packageupdate',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'UPDATED'), (2, 'IGNORED')], default=0),
        ),
    ]
