# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20170801_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageupdate',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
