# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_packageupdate_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageupdate',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Debian'), (1, 'Centos')], null=True),
        ),
    ]
