# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20170803_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageupdate',
            name='status',
        ),
    ]
