# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_remove_packageupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='auto_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.IntegerField(choices=[(0, 'UP TO DATE'), (1, 'UPDATES AVAILABLE'), (2, 'PENDING'), (3, 'INSTALL'), (4, 'ERROR')], default=3),
        ),
    ]
