# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20170809_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='update_interval',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
