# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('_type', models.IntegerField(choices=[(0, 'SSH Command')], default=0)),
                ('info', models.TextField()),
                ('extra_info', models.CharField(default='', max_length=255)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Server')),
            ],
        ),
    ]
