# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='_type',
            new_name='event_type',
        ),
    ]
