# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userland', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='servers_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='servers_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='customers_limit',
            field=models.IntegerField(default=0),
        ),
    ]
