# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userland', '0002_auto_20171012_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='base_credits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reseller',
            name='base_credits',
            field=models.IntegerField(default=1),
        ),
    ]
