# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userland', '0004_auto_20170726_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='server_limit',
            field=models.IntegerField(default=0),
        ),
    ]
