# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('hostname', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Up to date'), (1, 'Not updated')], default=0)),
            ],
        ),
    ]
