# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackageUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'UPDATED'), (1, 'PENDING'), (2, 'IGNORED')], default=1)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.IntegerField(choices=[(0, 'Debian'), (1, 'Centos')], null=True)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'UPDATED'), (1, 'PENDING'), (2, 'IGNORED')], default=0)),
                ('public_key', models.TextField(blank=True)),
                ('private_key', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('servers', models.ManyToManyField(blank=True, to='server.Server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='packageupdate',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Server'),
        ),
    ]
