# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='install',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
