# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170710_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servergroup',
            name='servers',
            field=models.ManyToManyField(blank=True, to='server.Server'),
        ),
    ]
