# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170720_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='install',
        ),
    ]
