# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170710_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servergroup',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
