# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_server_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.IntegerField(choices=[(0, 'Debian'), (1, 'Centos'), (2, 'Ubuntu'), (3, 'Unknown')], null=True),
        ),
    ]
