# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20170720_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='install',
            field=models.BooleanField(default=True),
        ),
    ]
