# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_update_updatepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='os',
            field=models.IntegerField(null=True),
        ),
    ]
