# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_server_install'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='id',
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
