# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20170720_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageupdate',
            name='status',
            field=models.IntegerField(choices=[(0, 'UPDATED'), (1, 'PENDING'), (2, 'IGNORED'), (3, 'ERROR')], default=1),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.IntegerField(choices=[(0, 'UPDATED'), (1, 'PENDING'), (2, 'IGNORED'), (3, 'ERROR')], default=3),
        ),
    ]
