# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20170718_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='updatepackage',
            name='package_name',
        ),
        migrations.AddField(
            model_name='server',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='updatepackage',
            name='version',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='updatepackage',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.Package'),
            preserve_default=False,
        ),
    ]
