# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20170719_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'UPDATED'), (1, 'PENDING'), (2, 'IGNORED')], default=1)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Package')),
            ],
        ),
        migrations.RemoveField(
            model_name='update',
            name='server',
        ),
        migrations.RemoveField(
            model_name='updatepackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='updatepackage',
            name='update',
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.IntegerField(choices=[(0, 'UPDATED'), (1, 'PENDING'), (2, 'IGNORED')], default=0),
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.DeleteModel(
            name='UpdatePackage',
        ),
        migrations.AddField(
            model_name='packageupdate',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Server'),
        ),
    ]
