# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20170719_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='public_key',
            field=models.TextField(blank=True),
        ),
    ]
