# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userland', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
