# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userland', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Reseller'), (2, 'Administrator')], default=0),
        ),
    ]
