# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userland', '0002_profile_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='server_limit',
            field=models.IntegerField(default=1),
        ),
    ]
